// Generated by CoffeeScript 1.10.0
(function() {
  var s;

  module.exports = function(sock, cb) {
    var notify, rds, route, t;
    t = null;
    notify = {};
    sock.onopen = function() {
      this.send(JSON.stringify({
        session: t = s()
      }));
      return cb();
    };
    rds = {};
    route = null;
    sock.onmessage = function(m) {
      var r;
      r = JSON.parse(m.data);
      if (r.status === "deleted") {
        delete rds[r.id];
      } else {
        rds[r.id] = r;
      }
      notify.ride(r);
      if (r.me) {
        return typeof notify.done === "function" ? notify.done(r) : void 0;
      }
    };
    return {
      query: function(q, d) {
        if (d) {
          notify.done = d;
        }
        if (q.route) {
          if (q.route === route) {
            return;
          } else {
            rds = {};
            route = q.route;
          }
        }
        sock.send(JSON.stringify(q));
        return this;
      },
      on: function(r) {
        notify.ride = r;
        return this;
      },
      get: function(id) {
        return rds[id];
      },
      sort: function(By) {
        return Object.keys(rds).map(function(r) {
          return rds[r];
        }).sort(function(a, b) {
          return a[By] - b[By];
        });
      },
      token: function() {
        return t;
      },
      close: function() {
        return sock.close();
      }
    };
  };

  s = function() {
    return 'xxxxxxxxxxxxxxxxxxx'.replace(/[xy]/g, function(c) {
      var r, v;
      r = Math.random() * 16 | 0;
      v = c === 'x' ? r : r & 0x3 | 0x8;
      return v.toString(16);
    });
  };

}).call(this);
